version: '1'
type: third-party
component:
  name: bosun-grafana-app
  owner:
    - freedom
  description: Extends the open-source Bosun plugin for grafana, adding query templating.
  awsProjectTag: skymetrics
  selfHosted: True
  license: MIT
  serviceClass: economy-class
  personalDataHandling: none # is your component handling personal data and in which way? One of (collecting/storing/processing/none)
  soxScope: False # is your component tracking company revenue? One of (True/False)
  paymentProcessing: False # is your component subject to PCI compliance? One of (True/False)
